# Generated by Django 2.2.7 on 2020-01-26 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0007_auto_20200125_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
    ]
