# Generated by Django 2.2.7 on 2020-01-27 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0013_auto_20200127_0256'),
        ('images', '0009_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
