# Generated by Django 2.2.7 on 2020-01-29 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0010_delete_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='total_likes',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
